<a href="https://colab.research.google.com/github/harish-coder/Deep-Learning/blob/master/Intro_to_Tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install tensorflow==1.14.0

     |████████████████████████████████| 109.2MB 78kB/s 
     |████████████████████████████████| 3.2MB 46.0MB/s 
     |████████████████████████████████| 491kB 29.2MB/s 
  Found existing installation: tensorboard 2.2.1
    Uninstalling tensorboard-2.2.1:
      Successfully uninstalled tensorboard-2.2.1
  Found existing installation: tensorflow-estimator 2.2.0
    Uninstalling tensorflow-estimator-2.2.0:
      Successfully uninstalled tensorflow-estimator-2.2.0
  Found existing installation: tensorflow 2.2.0
    Uninstalling tensorflow-2.2.0:
      Successfully uninstalled tensorflow-2.2.0


In [0]:
import tensorflow as tf

In [6]:
tf.__version__

'1.14.0'

## Create Tensorflow object Called Tensor

In [0]:
hello_constant = tf.constant("Hello World")

In [12]:
hello_constant

<tf.Tensor 'Const_2:0' shape=() dtype=string>

## IN 2.x there is no concept called session

In [13]:
with tf.Session() as sess:
  # Run the tf.constant operation in the session
  output = sess.run(hello_constant)
  print(output)

b'Hello World'


## Tensorflow

##### In TensorFlow, data isn’t stored as integers, floats, or strings. These values are encapsulated in an object called a tensor. In the case of hello_constant = tf.constant('Hello World!'), hello_constant is a 0-dimensional string tensor, but tensors come in a variety of sizes as shown below:

In [0]:
# A is a 0-dimensional int32 tensor
A = tf.constant(1234)

# B is a 1-dimensional int32 tensor
B = tf.constant([123,456,789])

# C is a 2-dimensional int32 tensor
C = tf.constant([ [123,456,789], [222,333,444] ])

In [16]:
C

<tf.Tensor 'Const_5:0' shape=(2, 3) dtype=int32>

In [19]:
with tf.Session() as sess:
  outputA = sess.run(A)
  outputC = sess.run(C)
  print(outputA)
  print(outputC)

1234
[[123 456 789]
 [222 333 444]]


## Session's feed_dict

In [21]:
## Passing the data in run time
## placeholder expecting the data in runtime
x = tf.placeholder(tf.string)

with tf.Session() as sess:
    output = sess.run(x, feed_dict={x: 'Harish ARUMUGAM'})
    print(output)

Harish ARUMUGAM


In [23]:
x = tf.placeholder(tf.int64)
with tf.Session() as sess:
    output = sess.run(x, feed_dict={x: 456879})
    print(output)

456879


In [25]:
x = tf.placeholder(tf.string)
y = tf.placeholder(tf.int32)
z = tf.placeholder(tf.float32)

with tf.Session() as sess:
    output_x = sess.run(x,feed_dict={x: 'Test String', y: 123, z: 45.67})
    output_y = sess.run(y, feed_dict={x: 'Test String', y: 123, z:45.67})
    output_z = sess.run(z, feed_dict={x: 'Test String', y: 123, z:45.67})
    print(output_x)
    print(output_y)
    print(output_z)

Test String
123
45.67


##### Note: If the data passed to the **feed_dict** doesn’t match the tensor type and can’t be cast into the tensor type, you’ll get the error “**ValueError: invalid literal for...**”

## TensorFlow Math

In [29]:
## Addition && Multiplication

X = tf.add(5,2)
Y = tf.multiply(2,5)
with tf.Session() as sess:
  addition = sess.run(X)
  mul = sess.run(Y)
  print(addition)
  print(mul)

7
10


In [31]:
## Below Operation not allowed in tensorflow.
tf.subtract(6,1.0)

TypeError: ignored

## Converting Types

In [32]:
tf.subtract(tf.constant(2.0),tf.constant(1))  

TypeError: ignored

In [33]:
c = tf.subtract(tf.cast(tf.constant(2.0), tf.int32), tf.constant(1))   # 1
with tf.Session() as sess:
    output = sess.run(c)
    print(output)

1


## Example

In [35]:
x = tf.constant(10)
y = tf.constant(2)
z = tf.subtract(tf.divide(x, y), 1)


with tf.Session() as sess:
    output = sess.run(z)
    print(output)


4.0


## TensorFlow Linear Functions

##### The most common operation in neural networks is calculating the linear combination of inputs, weights, and biases. As a reminder, we can write the output of the linear operation as:

# Y = xW+b

Here, W is a matrix of the weights connecting two layers. The output y, the input x, and the biases b are all vectors.

Weights and Bias in TensorFlow
The goal of training a neural network is to modify weights and biases to best predict the labels. In order to use weights and bias, you'll need a Tensor that can be modified. This leaves out tf.placeholder() and tf.constant(), since those Tensors can't be modified. This is where tf.Variable class comes in.

tf.Variable()

In [0]:
x = tf.Variable(5)

##### The tf.Variable class creates a tensor with an initial value that can be modified, much like a normal Python variable. This tensor stores its state in the session, so you must initialize the state of the tensor manually. You'll use the tf.global_variables_initializer() function to initialize the state of all the Variable tensors:

In [38]:
init = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init)
    print(sess.run(x))

5


The tf.global_variables_initializer() call returns an operation that will initialize all TensorFlow variables from the graph. You call the operation using a session to initialize all the variables as shown above. Using the tf.Variable class allows us to change the weights and bias, but an initial value needs to be chosen.

Initializing the weights with random numbers from a normal distribution is good practice. Randomizing the weights helps the model from becoming stuck in the same place every time you train it. You'll learn more about this in the next lesson, gradient descent.

Similarly, choosing weights from a normal distribution prevents any one weight from overwhelming other weights. We'll use the tf.truncated_normal() function to generate random numbers from a normal distribution.

## tf.truncated_normal()

In [0]:
n_features = 120
n_labels = 5
weights = tf.Variable(tf.truncated_normal((n_features, n_labels)))

In [40]:
weights

<tf.Variable 'Variable_1:0' shape=(120, 5) dtype=float32_ref>

In [41]:
init = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init)
    o=tf.truncated_normal((n_features, n_labels))
    print(o)

Tensor("truncated_normal_1:0", shape=(120, 5), dtype=float32)


The **tf.truncated_normal()** function returns a tensor with random values from a normal distribution whose magnitude is no more than 2 standard deviations from the mean.

Since the weights are already helping prevent the model from getting stuck, you don't need to randomize the bias. Let's use the simplest solution, setting the bias to 0.


## tf.zeros()

In [43]:
import numpy as np
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [44]:
np.ones((5,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [0]:
n_labels = 5
bias = tf.Variable(tf.zeros(n_labels))

## TensorFlow Softmax

## The softmax function squashes it's inputs, typically called logits or logit scores, to be between 0 and 1 and also normalizes the outputs such that they all sum to 1. This means the output of the softmax function is equivalent to a categorical probability distribution. It's the perfect function to use as the output activation for a network predicting multiple classes.


In [50]:
x = tf.nn.softmax([2.0, 1.0, 0.2])
with tf.Session() as sess:
  o = sess.run(x)
  print(o)


[0.65223986 0.23994564 0.10781453]


## Example

In [51]:

def run_2():
    output = None
    logit_data = [2.0,1.0,0.1]
    
    # Calculate the softmax of the logits
    softmax = tf.nn.softmax(logit_data)   
    
    with tf.Session() as sess:
        # Feed in the logit data
        output = sess.run(softmax)

    return output

print(run_2())

[0.6590012  0.24243298 0.09856589]


In [52]:
def run_2():
    output = None
    logit_data = [19,354,354,45,354,54]
    logits = tf.placeholder(tf.float32)
    
    # Calculate the softmax of the logits
    softmax = tf.nn.softmax(logits)   
    
    with tf.Session() as sess:
        # Feed in the logit data
        output = sess.run(softmax, feed_dict={logits: logit_data})

    return output

print(run_2())

[0.         0.33333334 0.33333334 0.         0.33333334 0.        ]


## One-Hot Encoding

#### Transforming your labels into one-hot encoded vectors is pretty simple with scikit-learn using LabelBinarizer. Check it out below!

In [0]:
import numpy as np
from sklearn import preprocessing

labels = np.array([1,5,3,2,1,4,2,1,3])


In [0]:
lb = preprocessing.LabelBinarizer()

In [55]:
## Here the encoder find the classes and assign one-hot vector
lb.fit(labels)

LabelBinarizer(neg_label=0, pos_label=1, sparse_output=False)

In [56]:
## And finally,transform the labels into one-hot encoder
lb.transform(labels)

array([[1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1],
       [0, 0, 1, 0, 0],
       [0, 1, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 1, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0]])

## Reduce Sum

In [57]:
x = tf.reduce_sum([1, 2, 3, 4, 5])  # 15
with tf.Session() as sess:
      output = sess.run(x)
      print(output)


15


## Natural Log

In [58]:
l = tf.log(100.0)
with tf.Session() as sess:
      output = sess.run(l)
      print(output)

4.6051702


## Example

#### Print the cross entropy using **softmax_data** and **one_hot_encod_label**

In [59]:
import tensorflow as tf

softmax_data = [0.7, 0.2, 0.1]
one_hot_data = [1.0, 0.0, 0.0]

softmax = tf.placeholder(tf.float32)
one_hot = tf.placeholder(tf.float32)

# Print cross entropy from session
cross_entropy = -tf.reduce_sum(tf.multiply(one_hot, tf.log(softmax)))

with tf.Session() as session:
    output = session.run(cross_entropy, feed_dict={one_hot: one_hot_data, softmax: softmax_data})
    print(output)

0.35667497
