<a href="https://colab.research.google.com/github/harish-coder/Deep-Learning/blob/master/TensorFlow2.0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install tensorflow==2.0.0

     |████████████████████████████████| 86.3MB 45kB/s 
     |████████████████████████████████| 3.8MB 41.8MB/s 
     |████████████████████████████████| 450kB 28.1MB/s 
  Created wheel for gast: filename=gast-0.2.2-cp36-none-any.whl size=7540 sha256=e542b2ce9f9fc643b5cac49843f90287df382d1c8bafc611d5269a3831fe2769
  Stored in directory: /root/.cache/pip/wheels/5c/2e/7e/a1d4d4fcebe6c381f378ce7743a3ced3699feb89bcfbdadadd
Successfully built gast
ERROR: tensorflow-probability 0.10.0 has requirement gast>=0.3.2, but you'll have gast 0.2.2 which is incompatible.
  Found existing installation: gast 0.3.3
    Uninstalling gast-0.3.3:
      Successfully uninstalled gast-0.3.3
  Found existing installation: tensorboard 2.2.2
    Uninstalling tensorboard-2.2.2:
      Successfully uninstalled tensorboard-2.2.2
  Found existing installation: tensorflow-estimator 2.2.0
    Uninstalling tensorflow-estimator-2.2.0:
      Successfully uninstalled tensorflow-estimator-2.2.0
  Found existing installation: t

## Version Check

In [2]:
import tensorflow as tf
print("TensorFlow version: {}".format(tf.__version__))
print("Keras version: {}".format(tf.keras.__version__))

TensorFlow version: 2.0.0
Keras version: 2.2.4-tf


## GPU/CPU Check

In [3]:
variable = tf.Variable([3, 3])
if tf.test.is_gpu_available():
    print('GPU')
    print('GPU #0?')
    print(var.device.endswith('GPU:0'))
else:
    print('CPU')

CPU


## Tensor Constant

In [4]:
ineuron = tf.constant(42)
ineuron

<tf.Tensor: id=8, shape=(), dtype=int32, numpy=42>

In [5]:
ineuron.numpy()

42

In [6]:
ineuron1 = tf.constant(1, dtype = tf.int64)
print(ineuron1)

tf.Tensor(1, shape=(), dtype=int64)


In [7]:
ineuron1.numpy()

1

In [8]:
ineuron_x = tf.constant([[4,2],[9,5]])
print(ineuron_x)

tf.Tensor(
[[4 2]
 [9 5]], shape=(2, 2), dtype=int32)


In [9]:
ineuron_x.numpy()

array([[4, 2],
       [9, 5]], dtype=int32)

In [10]:
print('shape:',ineuron_x.shape)
print(ineuron_x.dtype)

shape: (2, 2)
<dtype: 'int32'>


## Commonly used method is to generate constant tf.ones and the tf.zeros like of numpy np.ones & np.zeros

In [11]:
print(tf.ones(shape=(2,3)))

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)


In [12]:
print(tf.zeros(shape=(3,2)))

tf.Tensor(
[[0. 0.]
 [0. 0.]
 [0. 0.]], shape=(3, 2), dtype=float32)


In [13]:
import tensorflow as tf
const2 = tf.constant([[3,4,5], [3,4,5]]);tf
const1 = tf.constant([[1,2,3], [1,2,3]]);
result = tf.add(const1, const2);
print(result)

tf.Tensor(
[[4 6 8]
 [4 6 8]], shape=(2, 3), dtype=int32)


## Random constant

In [14]:
tf.random.normal(shape=(2,2),mean=0,stddev=1.0)

<tf.Tensor: id=25, shape=(2, 2), dtype=float32, numpy=
array([[ 1.8266308, -0.5547419],
       [-1.0055993, -0.550414 ]], dtype=float32)>

In [15]:
tf.random.uniform(shape=(2,2),minval=0,maxval=10,dtype=tf.int32)

<tf.Tensor: id=29, shape=(2, 2), dtype=int32, numpy=
array([[2, 7],
       [8, 5]], dtype=int32)>

## Declaring variables

In [16]:
var0 = 24 # python variable
var1 = tf.Variable(42) # rank 0 tensor
var2 = tf.Variable([ [ [0., 1., 2.], [3., 4., 5.] ], [ [6., 7., 8.], [9., 10., 11.] ] ]) #rank 3 tensor
var0, var1, var2

(24,
 <tf.Variable 'Variable:0' shape=() dtype=int32, numpy=42>,
 <tf.Variable 'Variable:0' shape=(2, 2, 3) dtype=float32, numpy=
 array([[[ 0.,  1.,  2.],
         [ 3.,  4.,  5.]],
 
        [[ 6.,  7.,  8.],
         [ 9., 10., 11.]]], dtype=float32)>)

## The datatype can be explicitly specified

In [17]:
float_var64 = tf.Variable(89, dtype = tf.float64)
float_var64.dtype

tf.float64

In [18]:
print(float_var64)

<tf.Variable 'Variable:0' shape=() dtype=float64, numpy=89.0>
